src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * Permet de dire a doctrine que cette entité doit gerer son cycle 
 * c'est a dire qu'a different instant de son cycle de vie on a relié des fctions
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date d'arrivée doit etre au bon format !")
     * @Assert\GreaterThan("today", message="la date d'arrivée doit etre ulterieur à la date d'aujourd'hui !",groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date de départ doit etre au bon format !")
     * @Assert\GreaterThan(propertyPath="startDate",message="La date d'arrivée doit etre anterieure à la date de depart!!")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * 
     * Callback appelé achaque fois qu'on crée une reservation
     * @ORM\Prepersist
     * @ORM\PreUpdate
     */

     // Si ma date de creation est vide; je creé une nouvelle dateTime a l'instant ou je le fais.
    public function prePersist(){

        if(empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }
      // Pour avoir le prix automatique de ma reservation:prix de l'annonce* nombre de jour(du sejour)

        if(empty($this->amount)){
            // pour faire ca il faut que je calcul le nombre de jours que de la reservation
            // je cree une fction getduration() pour avoir le nombre de jours exacte

            //$this->ad->getPrice() me donne le prix de l'annonce
            //$this->getDuration() me donne le nbre de jours 

           $this->amount = $this ->ad->getPrice() * $this->getDuration();


        }
    }
    public function getDuration(){

        // la je fais tt betement $diff= endDate() - startDate() pour avoir un objet de type dateInterval
        $diff = $this->endDate->diff($this->startDate);
        // là je recupere le nombre de jour ds mon objet dateInterval
        return $diff->days;
    }

    public function isBookableDates(){

        //1- il faut connaitre les dates qui sont impossibles a l'annonce

        $notAvailableDays = $this->ad->getNotAvailableDays();

        //2- il faut comparer les dates choisies avec les dates impossibles 

        $bookingDays = $this->getDays();// la je recupere les jours de ma reservation

        // je vais donc transformer ces objets datetime en un tableau qui contiendront des string facilement comparable 

        $formatDay = function ($day) {
                return $day->format('Y-m-d');
        };
         

        $days =array_map($formatDay,$bookingDays);


        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach($days as $day){
            // array_search est une fction qui me permet de chercher une info o sein d'un tableau qui prends comme premier parametre  l'information
            if(array_search($day,$notAvailable) !== false) return false;
        }
        return true;

    }

    /**
     * Permet de recuperer un tableau des journees qui correspondent à ma reservation
     * @return array un tableau d'objet dateTime representant les jours de la reservation
     */


    public function getDays(){

        $resultat = range(
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp) {
            return new \dateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);


        return $days;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields ={"email"},
 * message="Cette adresse mail est dejà utilisee,Veuillez choisir une autre")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre Prenom !")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre Nom !")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une Url valide !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;


    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les deux mots de passe ne sont pas identiques !")
     */
    public $passwordConfirm;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,minMessage="Votre introduction doit contenir au minimum 10 caratères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=50,minMessage="Votre introduction doit contenir au minimum 50 caratères !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;


    public function getFullName(){

        return "{$this->firstName} {$this->lastName}";

    }


    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */

    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstName;
    }

    public function setFirstname(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles(){

        // EXPLICATIONS:

        // fction toArray() transforme une arraycoolection en un tableau classique Php
        // fction map() va boucler sur chaque role qui se trouve ds l'entite role de la table des user et les transforme en quelque chose d'autres...ds notre cas le titre du role et donc getTitle()->Role_admin

        //$roles= $this->userRoles->toArray();

      // dump($roles); pour voir le contenu du premier $roles qui est un arraycollection avec des roles

        $roles = $this->userRoles->map(function($role){
            return $role ->getTitle();
        })->toArray();

        // Tous nos utilisateurs ont le role_user (c'est sur!) par contre certains parmi eux auront le role_user et le role_admin: comment faire? on ajoute juste : $roles[] = 'Role_User'

        $roles[] = 'ROLE_USER';

        return $roles;

       // dump($roles); et un deuxieme tableau qui contien juste une chaine de caractère "role_admin"!!
      // die();
        
        
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
        
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
        
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
     private $transformer;


    public function __construct(FrenchToDateTimeTransformer $transformer){

        $this->transformer = $transformer;

   }



    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate',TextType::class,$this->getConfiguration("Date d'arrivée","Votre date d'arrivée"))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de départ", "Votre date de départ"))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, "N'hesitez-pas à laisser un commentaire !!",["required" => false]));
         

         $builder ->get('startDate')->addModelTransformer($this->transformer);
         $builder ->get('endDate')->addModelTransformer($this->transformer);   
                      
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => [
                'Default',
                'front'
            ]
        ]);
    }
}

//["widget" => "single_text"] mis en option dans un champ dateType permet d'avoir un beau calendrier lol!!

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ad.title}} !{% endblock %}

{% block stylesheets %}
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />

{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="mt-3">  Réservez l'annonce : <em>{{ ad.title }}</em></h1>
    <p class="mt-3">Vous etes sur le point de reserver le bien de : <strong>{{ ad.author.fullname}}</strong>&nbspDites-nous tous on s'occupe du reste!!</p>
    {{ form_start(form)}}
        <div class="bg-light py-3 px-3">
           <h2 class="h4">Vos dates d'entrée et de depart !</h2>
            <div class="row mt-4">
                <div class="col-md-4">{{form_row(form.startDate)}}</div>
                <div class="col-md-4">{{form_row(form.endDate)}}</div>
            </div>
                <h4 class="mt-3">Montant du Sejour : <span id="amount">...</span>€</h4>
                <span id="days">0</span> nuit(s) à {{ad.price | number_format(2, ',',' ')}} € par nuit.
                <h2 class="mt-3">Vous avez un commentaire?</h2>
                <div class="col-md-6 mt-4">{{form_row(form.comment)}}</div>
          </div>
          <h2 class="mt-3">Vous avez terminé!!</h2>
          <p>Vacances de reve? Hebergement pour le boulot? Peu importe,On est avec vous !!</p>
         <button type="submit" class="btn btn-success mt-2">Je réserve !</button>
     {{form_end(form)}}
    </div> 
{% endblock %}

{% block javascripts %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>

 <script>
   $(document).ready(function(){

     $('#booking_startDate, #booking_endDate').datepicker({
         format : 'dd/mm/yyyy',
         datesDisabled:[
             {% for day in ad.notAvailableDays %}
              "{{day.format('d/m/Y')}}",
             {% endfor %}
         ],
         startDate:new Date()
     });

     $('#booking_startDate, #booking_endDate').on('change', CalculateAmount);
   });

   function CalculateAmount(){
     // on choppe les dates
     //const endDate = new Date($('#booking_endDate').val()); ici je recupere une chaine de caractere au format francais alors que javascript comprend que les dates au format internationale (année-mois-jour)! pour s'y faire on introduit la fction replace()

     const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
    // nous avons une date 23/08/2019 et on veut la transformée en 2019-08-23

    // on crée une expression regulière qui represente la date 23/08/2019:: \d+\/\d+\/\d{4}
    // apres on capture ce que l'on trouve ds l'expression reguliére::(\d+)\/(\d+)\/(\d{4})
    // apres on met l'expression regulière ds la fctionn replace. le $3-$2-$1 veut dire que je chope ds un premier tps l'année qui est en troisieme position ds mon expression regulière ,apres le mois et ensuite le jour.

     const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));

     if(startDate && endDate && startDate < endDate){

       const DAY_TIME = 24 * 60 * 60 * 1000; // le nombre de milliseconde ds une jrnée
       // si on fait startDate - endDate javascipt ne comprend pas parce que ce st des objetc datetime
       // par contre la fction getTimen de javascript associée a nos constantes nous donne un timestamp!!!
       const interval = endDate.getTime() - startDate.getTime(); // la j'ai le nombre de milliseconde du sejour
       const days = interval / DAY_TIME; // la j'ai le nombre de jours
       const amount = days * {{ ad.price }};
       // ici on gere automatiquement ds l'affichage twig le nombre de jours du sejour 
       $('#days').text(days);

       // ici on gere automatiquement ds l'affichage twig le montant que vaut le sejour
       $('#amount').text(amount.toLocaleString('fr-FR'));
     }

     
  };

 </script>

{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{booking.id}} {% endblock %}

{% block body %}

{% set ad = booking.ad %}

{% set author = ad.author %}

  <div class="container">
    <h1 class="my-5">Votre réservation (n°{{booking.id}})</h1>

    {% if app .request.query.get('withAlert')%}

      <div class="alert alert-success">
        <h4 class="alert-heading">Bravo ! </h4>

        <p>
          Votre réservation chez
          <strong>
            <a href="{{path('user_show',{'slug' : author.slug })}}">{{author.fullname}}</a>
          </strong>
          pour l'annonce
          <strong>
            <a href="{{path('ads_show',{'slug' : ad.slug })}}">{{ad.title}}</a>
          </strong>

          a bien été prise en compte  
        </p>
      </div>

    {% endif %}

    <div class="row">
      <div class="col">
         <div class="alert alert-light">
           <h2 class="text-center mb-5">Détails</h2>
           <dl class="row">
              <dt class="col-md-4">Numero</dt>
              <dd class="col-md-8">{{booking.id}}</dd>
              <dt class="col-md-4">Date d'arrivée</dt>
              <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
              <dt class="col-md-4">Date de départ</dt>
              <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
              <dd class="col-md-4">Nombre de nuit</dd>
              <dt class="col-md-8">{{booking.duration}}</dt>
              <dd class="col-md-4">Montant total</dd>
              <dt class="col-md-8">{{booking.amount| number_format(2, ',',' ')}}&nbsp€</dt>
              <dd class="col-md-4">Commentaire</dd>
              <dt class="col-md-8">{{booking.comment | default('Aucun commentaire')}}</dt>
           </dl>

           <hr>

           <h2 class="alert-heading">Votre hote</h2>
            
            <div class="row mb-3">
               <div class="col-3">
                 <img src="{{author.picture}}" class="avatar avatar-medium" alt="Avatar de {{author.fullname}}">
               </div>
               <div class="col-9">
                 <h4>
                    <a href="{{path('user_show', {'slug' : author.slug}) }}">{{ author.fullname}}</a>
                 </h4>

                 <span class="badge badge-primary">{{author.ads| length }}&nbsp annonces</span>
               </div>
            </div>
            {{author.description | raw}}

            <a href="{{path('user_show',{'slug':author.slug}) }}" class="btn btn-primary">Plus d'infos sur {{ author.firstname}}</a>
         </div>  
         <div class="alert alert-light" id="comment">
            <h2 class="alert-heading">Votre avis Compte !!!</h2>
            {% if date() > date(booking.endDate) %}

               {% set comment = booking.ad.getCommentFromAuthor(app.user) %}

              {% if comment is not null %}
                <blockquote>
                 {{comment.content}}
                </blockquote>
                <strong>Note :</strong> {% include 'partials/rating.html.twig' with {'rating':comment.rating}%}
              {% else %}

                {{form_start(form)}}
                {{form_widget(form)}}
                <button type="submit"class="btn btn-success">Confirmer</button>
                {{form_end(form)}}
              {% endif %}  
              
            {% else %}
            <p>Vous pourrez noté cette annonce à la fin de votre séjour!</p>
            {% endif %}
         </div>  
      </div>
      <div class="col">
        <div class="alert alert-light">
          <h2 class="alert-heading">Votre hebergement</h2>

          <h4 class="mt-5">
           <a href="{{path('ads_show', {'slug': ad.slug }) }}">{{ad.title}}</a>
          </h4>
          <img src="{{ad.coverImage}}" alt="Image de {{ad.title}}" class="img-fluid mb-3">

          {{ad.content | raw }}

          <a href="{{path('ads_show',{'slug': ad.slug}) }}" class="btn btn-primary">Pour plus d'information</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}