src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"title"},
 * message="Une autre annonce possède déjà ce titre!!"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\Length(min=10,max=255,minMessage="Le titre doit faire minimun 10 caractères!",
     * maxMessage="Le titre doit faire maximun 255 caractères!")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20,minMessage="L'introduction doit faire minimun 20 caractères!")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     *  @Assert\Length(min=50,minMessage="La description détaillée doit faire minimun 50 caractères!")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */

    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de recuperer un auteur par rapport a une annonce
     * @param User $author
     * @return Comment | null
     */

    public function getCommentFromAuthor(User $author){
     // On veut rechercher:Est-ce que parmi ts les commentaires qui sont liés à l'annonce j'ai un commentaire dt l'auteur est le mm que celui passé a ma fonction
     foreach($this->comments as $comment){
       // si l'auteur du commentaire est egale a mon auteur ds la fction, je retourn le commentaire
        if($comment->getAuthor() === $author) return $comment;
     }
        return null;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return float
     */
    public function getAvgRatings(){
     // 1) calculer la somme des notations
     // La fction array_reduce() reduit le tableau des commentaires en une seule valeur
     // $this->comments c'est un array collection qd on lui pass la fction toArray() il le reduit a 1 veritale tableau; apres je dois lui preciser comment je veux reduire ce tableau en lui passant une fction() qui recoit une variable $total et $comment qui est chaque commentaire recu
     // En gros je boucle sur le tableau des commentaires que je fournis ds $this->comments et on appele la function a  chaque fois en lui passant un total qui commence a 0 et le commentaire en lui mm:return $total + $comment->getRating(); elle retourne dc le total + la note qui est sur le commentaire: $comment->getRating()
     $sum = array_reduce($this->comments->toArray(),function($total,$comment){
         return $total + $comment->getRating();
     },0);
      
     // 2) calculer la moyenne
     //$moyenne = $sum / count($this->comments): ca c'est la moyenne au cas ou le commentaire existe sinn je suis entrain de diviser un nombre par 0 au cas ou je n'ai pas de commentaire. Pour eviter ca on rajoute: on s'assure que le nombre de commentaire est superieur a 0 count($this->comments)>0
     if(count($this->comments) > 0) return $sum / count($this->comments);

     return 0;
    }
   


    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponible pour cette annonce
     * @return array un tableau d'objets dateTime representant les jours d'occupations
     * 
     */

    public function getNotAvailableDays(){
        $notAvailableDays = [];

        foreach($this->bookings as $booking){

            //La je vais calculer les jours qui se trouvent entre la date d'arrivée et de depart $resultat= range(10,20,2): la fction     range() de php permet de determiner toutes les etapes qui permettent d'aller de 10 à 20 en sautant de $resulatt = [10,12,   14,16,18,20]    10 ds mon cas = $booking->getStartDate()->getTimestamp() 20=$booking->getEndtDate()->getTimestamp() 2= je   calcul 24h sous la forme de seconde 2=24h*60min*60seconde
              
             $resultat = range(
                 $booking->getStartDate()->getTimestamp(),
                 $booking->getEndDate()->getTimestamp(),
                 24*60*60); // est un tableau mais moi je veux avoir des jours

            // array_map est une fonction qui permet de transformer mon tableau de range() en un autre tableau qui sera le miroir de range avec des elements transformés.
            //array_map il faut lui preciser une fonction de transformation

            $days = array_map(function($dayTimestamp){
                return new \dateTime(date('Y-m-d', $dayTimestamp));
            },$resultat);

            // Dans $days j'ai donc la mm chose que $resultat sauf qu'il est en seconde, mais la je l'ai sous forme de l'ensemble des      jours sous la forme de dateTime qui sont entre le jour de depart et le jour d'arrivee d'une reservation
            

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;

    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Image;
use App\Form\AnnonceType;
use App\Repository\AdRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{

    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {
        $ads = $repo->findAll();
        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }


    /**
     * @Route("/ads/new",name="ads_create")
     * @IsGranted("ROLE_USER")
     * @return Response 
     */

    public function create(Request $request , ObjectManager $manager )
    {
        $ad = new Ad();

        $form =$this -> createForm(AnnonceType::class,$ad);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            foreach($ad->getImages()as $image){
                $image->setAd($ad);
                $manager->persist($image);

            }
             
            // je relie un auteur a une annonce
            $ad ->setAuthor($this->getUser());

            $manager ->persist($ad);
            $manager ->flush();

            $this->addFlash(
                'success',
                "l'annonce <strong> {$ad->getTitle()}</strong>  à bien été enrégistreé!!" 
            );

            return $this->redirectToRoute('ads_show',[
                'slug' =>$ad ->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig',[
            'form' => $form->createView()
        ]);
    }





    /**
     * 
     * @Route("/ads/{slug}/edit",name="ads_edit")
     * @Security("is_granted('ROLE_USER')and user===ad.getAuthor()",message="Vous n'etes pas l'auteur de cette    annonce,Pas de modification possible !")
     * @return Response
     * 
     */

    public function edit(Ad $ad,Request $request, ObjectManager $manager){

        $form = $this->createForm(AnnonceType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            //$manager = $this->getDoctrine()->getManager();
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "les modifications  ont bien été enrégistreés !!"
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig',[
            'form' => $form->createView(),
            'ad' => $ad
        ]);


    }


    

    /**
     * @Route("/ads/{slug}",name="ads_show")
     * @return Response
     */

    public function show($slug, AdRepository $repo)
    {
        // ici je recupere l'annonce qui correspond au slug
        $ad = $repo->findOneBySlug($slug);

        return $this->render('ad/show.html.twig', [
            'ad' => $ad

        ]);
    }



    /**
     * 
     * @Route("/ads/{slug}/delete",name="ads_delete") 
     * @Security("is_granted('ROLE_USER') and user===ad.getAuthor()", message="Vous n'etes pas l'auteur de cette    annonce,Pas de suppression possible !")
     * @param Ad $ad
     * @param ObjectManager $manager
     * @return Response
     * 
     */

    public function delete(Ad $ad, ObjectManager $manager)
    {
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée !"
        );

        return $this->redirectToRoute('ads_index');
    }

    
    
}

templates/ad/_ad.html.twig
{% set url = path('ads_show',{'slug': ad.slug}) %}
 
  <div class="col-md-4">
             <div class="card bg-light mb-3">
                 <div class="card-header text-center">
                     {{ ad.rooms }} chambres <strong>{{ ad.price | number_format(2, ',',' ') }} €  par nuit </strong><br>

                     {% if ad.comments |length > 0 %}
                       {% include 'partials/rating.html.twig' with {'rating':ad.avgRatings} %}
                     {% else %}
                     <small>Pas encore noté</small>
                     {% endif %}
                 </div>
                 <a href="{{ url }}">
                 <img src="{{ ad.coverImage }}" alt="Image de l'appartement" style="height:200px;width:100%; display:block">
                 </a>
                 
                 <div class="card-body">
                     <h4 class="card title text-center ">
                     <a href="{{ url }}"> {{ ad.title }}!</a>
                     </h4>
                     <p class="card-text">
                        {{ ad.introduction }}
                     </p>
                     <a href="{{ url }}" class="btn btn-primary float-right">En savoir plus</a>
                    {% if  app.user and app.user == ad.author %}
                     <a href="{{ path('ads_edit',{'slug': ad.slug })  }}" class="btn btn-secondary">Modifier l'annonce</a>
                    {% endif %}
                 </div>
             </div>
         </div>
  

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}

    <p>Ici vous pouvez ajouter vos propres images!</p>

    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
     <button type="button" id="add-image" class="btn btn-primary">
     <i class="fas fa-plus mr-2"></i>
     Ajouter une image
     </button>
    </div>

 {% endblock %}

{% block _annonce_images_entry_row %}
    {{ form_widget(form)}}
{% endblock %}


{% block _annonce_images_entry_widget %}

<div class="form-group" id="block_{{id}}">
  <div class="row">
        <div class="col-10">
          <div class="row">
            <div class="col">
            {{ form_widget(form.url)}}
            {{form_errors(form.url)}}
            </div>
            <div class="col">
            {{ form_widget(form.caption)}}
            {{form_errors(form.caption)}}
            </div>
          </div>
       </div>
       <div class="col-2">
         <button type="button " data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
       </div>
  </div>
   
</div>

{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Edition d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}


{% block body %}

<div class="container">
<h1>Modifier l'annonce : {{ ad.title }} </h1>
 {{form_start(form)}}

{{form_widget(form)}}

<button type="submit" class="btn btn-primary">Editer l'annonce</button>
 {{form_end(form)}}

</div>


{% endblock %}

{% block javascripts %}
<script src="/js/ad.js"> </script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}

<div class="container mt-5">

        <h1 class="my-5">Voici la liste de nos annonces</h1>
        <div class="row">
        {% for ad in ads %}
        {% include 'ad/_ad.html.twig'%}
        {% endfor %}
        </div>
</div>


{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} Creation d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

<div class="container">
<h1 class="my-5">Creer une nouvelle annonce </h1>
 {{form_start(form)}}
 <div class="row">
   <div class="col">
    <div class="alert alert-light">
    <h2>Informations Générales</h2>
    <hr>
    {{form_row(form.title)}}
    {{form_row(form.slug)}}
    {{form_row(form.price)}}
    {{form_row(form.rooms)}}
    </div>
    <div class="alert alert-light">
      <h2>Détails de l'annonce</h2>
      <hr>
      {{form_row(form.introduction)}}
      {{form_row(form.content)}}
    </div>
   </div>
   <div class="col">
    <div class="alert alert-light">
    <h2>Image de l'annonce</h2>
    <hr>
        {{form_row(form.coverImage)}}
        {{form_row(form.images)}}
    </div>
   </div>
 </div>
  <div class="alert alert-light clearfix">
    <h2 class="alert-heading">Sauvegarder mon annonce</h2>
    <button type="submit" class="btn btn-primary float-right"><i class="fas fa-save mr-2"></i>Creer la nouvelle annonce</button>
  </div>  
 {{form_end(form)}}
</div>
 {% endblock %}
{% block javascripts %}
<script src="/js/ad.js"></script>   
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}
 {{ad.title}}
{% endblock %}


{% block body %}

<div class="ad-title" style="background-image: url({{ad.coverImage}})">

<div class="container">
<h1>{{ad.title}}</h1>
<p>{{ad.introduction | raw }}</p>
<p class="h2">
<strong>{{ad.rooms}} chambres</strong> pour <strong>{{ad.price | number_format(2, ',',' ') }}&nbsp€</strong> par nuit
</p>
<a href="{{path('booking_create',{'slug': ad.slug }) }}" class="btn btn-primary">Reserver</a>

 {% if  app.user and app.user == ad.author %}
<a href="{{ path('ads_edit',{'slug': ad.slug })  }}" class="btn btn-secondary">Modifier l'annonce</a>
<a href="{{path('ads_delete',{'slug': ad.slug }) }}" class="btn btn-danger" onclick="return confirm(`Etes-vous certain(e) de vouloir supprimer l'annonce : {{ad.title}} ?`)">Supprimer l'annonce</a>
{% endif %}

</div>

</div>

<div class="container">
  <div class="row">

   <div class="col-md-8 mb-3">
   {{ad.content | raw }}

   <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          {% for image in ad.images %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first%}class="active"{% endif %}></li>

         {% endfor %}
           
        </ol>
        <div class="carousel-inner">
        {% for image in ad.images %}
            <div class="carousel-item {% if loop.first %}active{% endif %}">
            <img src="{{image.url}}" class="d-block w-100" alt="carousel des images">

            <div class="carousel-caption d-none d-md-block">
            <h5>{{ad.title}}</h5>
            <p>{{image.caption}}</p>
            </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
      </div>

      <hr>

      {%if ad.comments | length > 0 %}

      <h2 class="mb-3">Commentaires de nos voyageurs</h2>

      <div class="alert alert-info">
         <h4 class="alert-heading text-center">
            <div class="row align-items-center">
              <div class="col">Note globale donnée par nos voyageurs 
              </div>    
              <div class="col">{% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                 <br>
                 <small>(Calculée sur {{ad.comments | length}} avis !)</small>
              </div>
            </div>
         </h4>
      </div>

      {% for comment in ad.comments %}
        <div class="bg-light rounded mb-3 py-3 px-3">
          <strong>{{ comment.author.firstname}}</strong> a révélé :
          <blockquote>
            {{comment.content}}
          </blockquote>
          <strong>Note :</strong>
          {% include 'partials/rating.html.twig' with {'rating':comment.rating} %}
         
        </div>
      {% endfor %}
      {% else %}
      <h2>Cette annonce n'a pas encore recu de commentaires</h2>
      {% endif %}

   </div>
   <div class="col">
     {% set a = ad.author %}
      <div class="row mb-3 align-items-center">
      <div class="col-3">
       <a href="{{ path('user_show',{'slug': a.slug })}}">
        <img src="{{ a.picture }}" alt="avatar de {{ a.fullName }}" class="avatar avatar-medium">
      </a>
      </div>
       <div class="col">
        <a href="{{ path('user_show',{'slug': a.slug })}}">
          <h3>{{a.fullName}}</h3>
        </a>
        <span class="badge badge-primary">{{ a.ads |length }} annonces
        </span>
       </div>
      </div>
      <p>{{ a.description | raw }}</p>
   </div>

  
  </div>
</div>




{% endblock %}